language: node_js

node_js:
  - stable

dist: trusty
install:
  - npm ci    
script:
  - npm test

after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls	
  
notifications:
  email: true

after_success: 'npm run coverage'
after_fail: 'npm run coverage'
