language: node_js

node_js:
  - stable
env:
  - CI=true
cache:
  directories:
    - node_modules

script:
  - npm test -- --coverage
  - npm run build

after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
  
notifications:
  email: true

after_success: 'npm run coverage'
after_fail: 'npm run coverage'
