language: node_js

node_js:
  - stable
env:
  - CI=true
cache:
  directories:
    - node_modules

script:
  - npm test

after_script:
  - npm run coveralls
  
notifications:
  email: true

after_success: 'npm run coverage'
after_fail: 'npm run coverage'
