language: node_js

node_js:
  - stable
env:
  - CI=true
cache:
  directories:
    - node_modules

script:
  - npm run build
  - npm test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: true

after_success: 'npm run coverage'
after_fail: 'npm run coverage'
